parameters:
    oro_comment.form.type.comment.class:       Oro\Bundle\CommentBundle\Form\Type\CommentType
    oro_comment.form.handler.comment.class:    Oro\Bundle\CommentBundle\Form\Handler\CommentHandler
    oro_comment.api.form.handler.class:        Oro\Bundle\CommentBundle\Form\Handler\CommentApiHandler

services:
    oro_comment.form.type.comment:
        class: %oro_comment.form.type.comment.class%
        tags:
            - { name: form.type, alias: oro_comment }

    oro_comment.form.type.comment_api:
        class: %oro_note.form.type.note_api.class%
        arguments:
            - @oro_entity_config.config_manager
        tags:
            - { name: form.type, alias: oro_comment_api }

    oro_comment.form.comment:
        class: Symfony\Component\Form\Form
        factory_method: createNamed
        factory_service: form.factory
        arguments:
            - 'oro_comment_form'
            - 'oro_comment'

    oro_comment.form.comment.api:
        class: Symfony\Component\Form\Form
        factory_method: createNamed
        factory_service: form.factory
        arguments:
            - ~
            - 'oro_comment_api'

    oro_comment.form.handler.note:
        class: %oro_comment.form.handler.comment.class%
        scope: request
        arguments:
            - @oro_comment.form.comment
            - @request
            - @doctrine.orm.entity_manager

    oro_comment.api.form.handler:
        class: %oro_comment.api.form.handler.class%
        scope: request
        arguments:
            - @oro_comment.form.comment.api
            - @request
            - @doctrine.orm.entity_manager
            - @oro_entity_config.config_manager
