parameters:
    oro_comment.migration.extension.comments.class: Oro\Bundle\CommentBundle\Migration\Extension\CommentExtension

services:
    oro_comment.migration.extension.comments:
        class: %oro_comment.migration.extension.comments.class%
        tags:
            - { name: oro_migration.extension, extension_name: comments }
