parameters:
    oro_comment.migration.extension.comment.class:    Oro\Bundle\CommentBundle\Migration\Extension\CommentExtension
    oro_comment.entity_generator.extension.class:     Oro\Bundle\CommentBundle\Tools\CommentEntityGeneratorExtension
    oro_comment.entity_config_dumper.extension.class: Oro\Bundle\CommentBundle\Tools\CommentEntityConfigDumperExtension
    oro_comment.form.type.comment.class:              Oro\Bundle\CommentBundle\Form\Type\CommentType
    oro_comment.form.handler.comment.class:           Oro\Bundle\CommentBundle\Form\Handler\CommentHandler
    oro_comment.placeholder.filter.class:             Oro\Bundle\CommentBundle\Placeholder\PlaceholderFilter

services:
    oro_comment.migration.extension.comment:
        class: %oro_comment.migration.extension.comment.class%
        tags:
            - { name: oro_migration.extension, extension_name: comment }

    oro_comment.entity_generator.extension:
        class: %oro_comment.entity_generator.extension.class%
        tags:
            - { name: oro_entity_extend.entity_generator_extension }

    oro_comment.entity_config_dumper.extension:
        class: %oro_comment.entity_config_dumper.extension.class%
        parent: oro_entity_extend.entity_config_dumper.extension.association
        tags:
            - { name: oro_entity_extend.entity_config_dumper_extension }

    oro_comment.form.type.comment:
        class: %oro_comment.form.type.comment.class%
        tags:
            - { name: form.type, alias: oro_comment }

    oro_comment.form.handler.note:
        class: %oro_comment.form.handler.comment.class%
        scope: request
        arguments:
            - @oro_comment.form.type.comment
            - @request
            - @doctrine.orm.entity_manager

    oro_comment.form.comment:
        class: Symfony\Component\Form\Form
        factory_method: createNamed
        factory_service: form.factory
        arguments:
            - 'oro_comment_form'
            - 'oro_comment'

    oro_comment.placeholder.filter:
        class: %oro_comment.placeholder.filter.class%
        arguments:
            - @oro_entity_config.config_manager
