parameters:
    oro_comment.migration.extension.comment.class:    Oro\Bundle\CommentBundle\Migration\Extension\CommentExtension
    oro_comment.entity_generator.extension.class:     Oro\Bundle\CommentBundle\Tools\CommentEntityGeneratorExtension
    oro_comment.entity_config_dumper.extension.class: Oro\Bundle\CommentBundle\Tools\CommentEntityConfigDumperExtension
    oro_comment.comment.manager.class:                Oro\Bundle\CommentBundle\Entity\Manager\CommentManager

services:
    oro_comment.migration.extension.comment:
        class: %oro_comment.migration.extension.comment.class%
        tags:
            - { name: oro_migration.extension, extension_name: comment }

    oro_comment.entity_generator.extension:
        class: %oro_comment.entity_generator.extension.class%
        tags:
            - { name: oro_entity_extend.entity_generator_extension }

    oro_comment.entity_config_dumper.extension:
        class: %oro_comment.entity_config_dumper.extension.class%
        parent: oro_entity_extend.entity_config_dumper.extension.association
        tags:
            - { name: oro_entity_extend.entity_config_dumper_extension }

    oro_comment.comment.manager:
        class: %oro_comment.comment.manager.class%
        arguments:
            - @doctrine
            - @oro_security.security_facade
            - @oro_locale.formatter.name
            - @oro_datagrid.extension.pager.orm.pager
            - @oro_config.user
