parameters:
    oro_comment.migration.extension.comment.class: Oro\Bundle\CommentBundle\Migration\Extension\CommentExtension

services:
    oro_comment.migration.extension.comment:
        class: %oro_comment.migration.extension.comment.class%
        tags:
            - { name: oro_migration.extension, extension_name: comment }
