parameters:
#    oro_comment.example.class: Oro\Bundle\CommentBundle\Example

services:
#    oro_comment.example:
#        class: %oro_comment.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
