api:
    entities:
        Oro\Bundle\CommentBundle\Entity\Comment:
            fields:
                target:
                    description: A record to which the Comment record belongs to
                    data_type: association:manyToOne
            subresources:
                target:
                    actions:
                        get_subresource:
                            documentation: Get full information about a record to which the comment belongs to
                        get_relationship:
                            documentation: Get a record to which the comment belongs to
                        update_relationship:
                            documentation: Update a record to which the comment belongs to

